# Generated by Django 2.0.4 on 2018-05-08 19:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='text'),
        ),
    ]
