# Generated by Django 2.0.4 on 2018-05-08 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20180508_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='added',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
