# Generated by Django 2.0.4 on 2018-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_auto_20180508_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(),
        ),
    ]
