# Generated by Django 2.0.4 on 2018-05-11 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_auto_20180509_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
